### ISSUE TITLE
The modify function is not working. 

### ISSUE THREAD

**Issue by Expire0** [Expire0/expire0-passwordApp#18]
Error :Traceback (most recent call last):
  File "getpass.py", line 38, in <module>
    classm.mod()
  File "/home/app/modules/classm.py", line 80, in mod
    cur.execute(data0)
pysqlcipher3.dbapi2.OperationalError: no such column: test67

Steps to reproduce 
1. add a bogus entry to the db 
2. retrieve the bogus entry and take note of the id 
3. use the modify menu option 
4. specify a new password 
5. enter the id of the record

**Comment by iamrahul1024** [comment]
Hi can you elaborate on this isssue

**Comment by Expire0** [comment]
@iamrahul1024 Need a function to modify an existing password entry in the db.  The db is sqlite.  The other functions are working to insert, delete etc. The modify function is generating a error
